Experiment_name: mediapipe_ShiftGCN_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/mediapipe/train_data_joint.npy
  label_path: ./data/mediapipe/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/mediapipe/val_data_joint.npy
  label_path: ./data/mediapipe/val_label.pkl

# model
model: model.shift_gcn.Model
model_args:
  num_class: 2
  num_point: 33
  num_person: 1
  graph: graph.mediapipe_pose.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [60, 80, 100]

# training
device: [0]
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 140
nesterov: True
